# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/error_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 388)
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setGeometry(QtCore.QRect(-20, -10, 461, 441))
        self.centralWidget.setStyleSheet("#centralWidget {\n"
"    background: center url(:/think.jpg);\n"
"}")
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(10, -20, 481, 451))
        self.pushButton.setStyleSheet("background-color: rgba(230, 153, 0, 200)")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.invalid_data_label_2 = QtWidgets.QLabel(self.centralWidget)
        self.invalid_data_label_2.setGeometry(QtCore.QRect(40, 70, 361, 171))
        self.invalid_data_label_2.setStyleSheet("font: 16pt \"Comfortaa\";\n"
"background-color: rgba(207, 69, 0, 200);\n"
"color: black;")
        self.invalid_data_label_2.setScaledContents(False)
        self.invalid_data_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.invalid_data_label_2.setObjectName("invalid_data_label_2")
        self.button_ok = QtWidgets.QPushButton(self.centralWidget)
        self.button_ok.setGeometry(QtCore.QRect(40, 280, 361, 31))
        self.button_ok.setStyleSheet("font: 14pt \"Comfortaa\";\n"
"background-color: rgb(204, 68, 0)")
        self.button_ok.setObjectName("button_ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.invalid_data_label_2.setText(_translate("Dialog", "Невозможные данные!\n"
"Проверьте\n"
"введенные числа!"))
        self.button_ok.setText(_translate("Dialog", "OK, сейчас проверю"))
from resources.resources import *
